spring:
  application:
    name: rate-limiter-java

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: rate-limiter-java
    description: Rate Limiter com Token Bucket e Sliding Window
    version: 0.0.1-SNAPSHOT

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

rate-limiter:
  algorithm: ${RATE_LIMITER_ALGORITHM:token-bucket}
  capacity: ${RATE_LIMITER_CAPACITY:10}
  refill-rate-per-second: ${RATE_LIMITER_REFILL_RATE_PER_SECOND:5}
  window-size-millis: ${RATE_LIMITER_WINDOW_SIZE_MILLIS:60000}